server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://whereup.c23up8mnq53r.ap-northeast-2.rds.amazonaws.com:3306/whereupdb
    username: upadmin
    password: skuwhereup

  jpa:
    show-sql: true
    database: mysql
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      
aws:
  access-key: AKIATQGI7YZS43KECDEB
  secret-key: 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
  region: ap-northeast-2
  s3:
    bucket-name: whereupp-s3
    url: whereupp-s3.s3.ap-northeast-2.amazonaws.com
  cloudfront:
    url: d1pssi2485491c.cloudfront.net

kakao:
  client-id: 86196b89e589d2d9a6a911881aacb3c2
  client-secret: GWhpk5o3xavmHFtwn5aXVKht2ey0RiwW
  client-authentication-method: client_secret_post # 인가코드로 엑세스 토근 요청할 때 방법 정의
  authorization-grant-type: authorization_code
  redirect-uri: http://localhost:9000/auth/kakao/callback
