server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    database: mysql
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    url: ${AWS_S3_URL}
  cloudfront:
    url: ${AWS_CLOUDFRONT_URL}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  client-authentication-method: client_secret_post # 인가코드로 엑세스 토근 요청할 때 방법 정의
  authorization-grant-type: authorization_code
  redirect-uri: ${KAKAO_REDIRECT_URI}
